name: 博客自动化部署


on:
  push:
    branches:
      - master # default branch

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: 拉取代码
      - uses: actions/checkout@v2

      - name: 指定node版本
        uses: actions/setup-node@v1
        with:
          node-version: '14.16.0'
      - name: 将npm配置为使用 https
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/
      
      - name: 安装依赖
        run: npm i

      - name: 编译构建
        run: npm run build

      - name: 发布
      - run: npm run deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./dist