name: 博客自动化部署
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v2
      
      
      - name: 安装依赖
        run: npm i

      - name: 编译构建
        run: npm run build

      - name: 发布
        uses: peaceiris/actions-gh-pages@v3
        run: npm run deploy
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./dist